name: Hawksolo migration - DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      destroy:
        description: Run IAC destroy
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: dojo360/dojo-terraform-workflows/.github/workflows/pipeline-apply.yml@cca6d0cb6438869ef3d117ae4c492470852cb3c2
    with:
      environment_name: dev
      optumfile_path: "UHC_HAWK_AZURE/gcm-azu-iac/terraform/hawksolorg/environments/optumfiles/dev.json"
      optumfile_runner: "uhg-runner"
      validate_runner: "uhg-runner"
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      cloud_provider: "azure"
    secrets:
      AZ_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  notify:
    runs-on: uhg-runner
    needs: deploy
    if: always()
    steps:
      - name: Send deployment notification email
        uses: uhg-pipelines/epl-send-mail@v1
        with:
          subject: "[DEPLOYMENT] ${{ github.repository }} - ${{ needs.deploy.result }}"
          from: notifications@github.com
          to: madarsh@optum.com
          priority: high
          body: |
            The deployment to the *dev* environment has completed with status: *${{ needs.deploy.result }}*.
            Details:
            - Environment: dev
            - Action Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          content_type: text/plain

